# Generated by Django 4.0.3 on 2022-05-08 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('img_url', models.CharField(max_length=2083)),
                ('phone_no', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('hr_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('r', models.IntegerField(default=0)),
            ],
        ),
    ]
